### ISSUE TITLE
Document permission issue

### ISSUE THREAD

**Issue by maximbert** [pandastrike/panda-sky#52]
Max: when trying to deploy I got the following error (below)
_David made me an admin (in AWS) as quickfix_
David: I've never encountered the permission issue. That will need to be called out in the docs

```
# sky publish staging
Scanning AWS for current deploy.
Existing stack detected. Updating.
Waiting for deployment to be ready.
Stack creation failed. Aborting. UPDATE_ROLLBACK_IN_PROGRESS The following resource(s) failed to create: [DiscoveryGetLambdaHandler, BlurbGetLambdaHandler, BlurbsPostLambdaHandler, BlurbDeleteLambdaHandler, DiscoveryOptionsMethod].
Error
    at Object.<anonymous> (/Users/max/.nvm/versions/node/v4.7.0/lib/node_modules/panda-sky/lib/aws/cloudformation.js:122:19)
    at [object Generator].next (native)
    at /Users/max/.nvm/versions/node/v4.7.0/lib/node_modules/panda-sky/node_modules/fairmont/node_modules/fairmont-helpers/lib/promise.js:91:26
    at step (/Users/max/.nvm/versions/node/v4.7.0/lib/node_modules/panda-sky/node_modules/fairmont/node_modules/fairmont-helpers/lib/promise.js:81:20)
    at /Users/max/.nvm/versions/node/v4.7.0/lib/node_modules/panda-sky/node_modules/fairmont/node_modules/fairmont-helpers/lib/promise.js:90:22
    at process._tickDomainCallback (node.js:428:9)
```

**Comment by automatthew** [comment]
It's not clear from the OP how this is a permissions problem.
