### ISSUE TITLE
Failed to deploy to new "testing" env

### ISSUE THREAD

**Issue by maximbert** [pandastrike/panda-sky#60]
Not sure what happened here, failed to deploy to a brand-new `testing` environment

```
sky build && sky publish testing
Scanning AWS for current deploy.
No deployment detected. Preparing Panda Sky infrastructure.
Creating fresh stack.
Waiting for deployment to be ready.
Stack creation failed. Aborting. ROLLBACK_IN_PROGRESS undefined
Error
    at Object.<anonymous> (/Users/max/.nvm/versions/node/v4.3.2/lib/node_modules/panda-sky/lib/aws/cloudformation.js:110:19)
    at [object Generator].next (native)
    at /Users/max/.nvm/versions/node/v4.3.2/lib/node_modules/panda-sky/node_modules/fairmont/node_modules/fairmont-helpers/lib/promise.js:91:26
    at step (/Users/max/.nvm/versions/node/v4.3.2/lib/node_modules/panda-sky/node_modules/fairmont/node_modules/fairmont-helpers/lib/promise.js:81:20)
    at /Users/max/.nvm/versions/node/v4.3.2/lib/node_modules/panda-sky/node_modules/fairmont/node_modules/fairmont-helpers/lib/promise.js:90:22
    at process._tickDomainCallback (node.js:407:9)
```

**Comment by automatthew** [comment]
Can't troubleshoot from this info.  Closing.
